name: podinfo
image:
  repository: ghcr.io/stefanprodan/podinfo
blueGreen:
  blue:
    replicaCount: 2
    tag: 5.1.4
    color: "#34577c"
  green:
    replicaCount: 2
    tag: 5.1.4
    color: "#00ff00"
canary:
  replicaCount: 3
  tag: 5.1.4
  color: "#ff9900"
prod:
  replicaCount: 7
  tag: 5.1.4
  color: "#0000ff"
serviceAccount:
  create: false
  name: ""
  annotations: {}
  automount: true
service:
  port: 80
  targetPort: 9898
ingress:
  host: podinfo.example.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /