apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.color }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      version: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.color }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9898
