apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP
